# Configuration file location on the Wii U SD card:
#   SD:/wiiu/ax88179/config.ini

[dhcp]
# DHCP mode:
#   keep_first = Use DHCP for the first successful connection, then reuse
#                the assigned IP configuration for the rest of the Aroma session.
#
#   always     = Perform a new DHCP negotiation after every title transition.
#
# Valid values: keep_first, always
mode=keep_first

[debug]
# 0 = désactivé
# 1 = socket/connect/bind/DNS/ioctl/select/etc.
# 2 = verbeux, incluant send/recv
shim_trace=2

[compat]
# ax = DNS through lwIP/AX88179
# system = leave DNS to nsysnet/Inkay
dns=system
